create table if not exists "Monkeys"."Genre"
(
	"Id" int primary key generated by default as identity not null,
	"GenreName" varchar(30) not null,
	"IsChecked" bool default false
);

create table if not exists "Monkeys"."Publishers"
(
	"Id" int primary key generated by default as identity not null,
	"PublisherName" varchar(35) not null
);

create table if not exists "Monkeys"."Authors"
(
	"Id" int primary key generated by default as identity not null,
	"FirstName" varchar(60) not null,
	"LastName" varchar(60) not null,
	"MiddleName" varchar(60) not null,
	"Birthday" date not null
);

create table if not exists "Monkeys"."Books"
(
	"Id" int primary key generated by default as identity not null,
	"BookName" varchar(100) not null,
	"PublicationYear" date not null,
	"PublisherId" int not null,
	"AuthorId" int not null,
	"PopularityRating" int check ("PopularityRating" > 0 and "PopularityRating" < 11) default 0,
	
	constraint "FK_Book_To_Publisher" foreign key ("PublisherId") references "Monkeys"."Publishers"("Id"),
	constraint "FK_Book_To_Author" foreign key ("AuthorId") references "Monkeys"."Authors"("Id")
);

create table if not exists "Monkeys"."Book_Genre"
(
	"Id" int primary key generated by default as identity,
	"BookId" int,
	"GenreId" int,
	
	constraint "FK_Book_Genre_To_Book" foreign key("BookId") references "Monkeys"."Books"("Id"),
	constraint "FK_Book_Genre_To_Genre" foreign key("GenreId") references "Monkeys"."Genre"("Id")
);

insert into "Monkeys"."Genre" ("Id","GenreName")
overriding system value
values 
(1,'Ужасы'),
(2,'Фантастика'),
(3,'Комедия'),
(4,'Фэнтези'),
(5,'Научная'),
(6,'Обучающее');